#!/bin/bash
filename="/etc/passwd"
while read -r line; do
	name="$line"
	login=$(echo $name | sed "s/:.*//g")
	uid=$(echo $name | cut -f 3 -d:)
	path=$(echo $name | cut -f 6 -d:)
	printf "%s          %s         %s\n" $login $uid $path
done < "$filename"
