#!/bin/bash
check_vim()
{
	if [ -f /usr/bin/vim ]; then
		only_sublivim
	else
		echo "Vim seems not to be installed on your system... Do you want to install it ? [Y/n] "
		read choice2
		if [ $choice2 == "Y" || $choice2 == "y" ]; then
			su -c "apt install vim"
			only_sublivim
		else
			echo "Nothing have been installed"
		fi
	fi
}

check_zsh()
{
	only_ohmyzsh
	if [ $SHELL !=  "/bin/zsh" ]; then
		echo "ZSH does not seems to be your actual shell... Do you want to change that ? [Y/n]"
		read choice3
		if [[ ($choice3 == "y") || ($choice3 == "Y") ]]; then
			su -c "chsh $USER -s /bin/zsh"
			echo "You will be unlogged,press [ENTER], please re-run the script after"
			read tmp
			su -c "pkill -u $USER"
		fi
	fi
}

only_vim()
{
su -c "apt install vim"	
}

only_zsh()
{
	su -c "apt install zsh"
}

only_sublivim()
{
	curl https://raw.githubusercontent.com/reversTeam/Sublivim/master/installer.sh | sh
}

only_ohmyzsh()
{
	sh -c "$(curl -fssL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

echo "
#####                                                                      #####
#                                                                              #
#    #   #  #   #     #####  #   #  #### #####  ##   #     #     ####  #####   #
#    ## ##   # #        #    ##  #  #      #   #  #  #     #     #...  #  #    #
#    # # #    #         #    # # #    #    #   ####  #     #     #     ####    #
#    #   #    #       #####  #  ##  ####   #   #  #  ####  ####  ####  #   #   #
#                                                                              #
#####                                                                      #####"

echo "What do you want to do ?"
printf "1) Install everything (zsh, OhMyZsh, vim, Sublivim)\n2) Install only zsh\n3) Install only OhMyZsh\n4) Install only vim\n5) Install only Sublivim\n6) Quit\n"
echo "Choose a number then press [Enter]"
read choice
echo "Your choice is $choice"
case $choice in 
	"1")
		su -c "apt install zsh vim"
		check_zsh
		only_ohmyzsh
		only_sublivim
	;;
	"2")
		only_zsh
	;;
	"3")
		only_ohmyzsh
	;;
	"4")
		only_vim
	;;
	"5")
	check_vim
	only_sublivim
	;;
	"6")
		exit
	;;
esac


















